### ISSUE TITLE
Cron-based Request Scheduler

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#10]
We should have a cron-based request scheduler that is native to BEERGARDEN. IT is often the case that a person may want to run a request (particularly an INFO request) once every x seconds, minutes, hours or days. Since BEERGARDEN helps people run those commands, it should also allow them to schedule the commands to run.

Once combined with webhooks, this will be really cool.

**Comment by loganasherjones** [comment]
@hazmat345 I'm thinking about using APScheduler. It seems like it has all the features we want and would be pretty forwards compatible for the AsyncIO stuff we want to do in the future.

 https://apscheduler.readthedocs.io/en/latest/index.html

**Comment by loganasherjones** [comment]
Okay, I have some major pieces of this done now. I'm going to layout the checklist of what else needs to be done in order to mark this one complete and try to keep track of it here:

- [ ] Add PATCH support for pausing/unpausing/updating a job.
- [ ] Add Swagger documentation for PATCH job when it is created
- [ ] Add brewtils support for CRUD jobs
- [ ] Add documentation to beer-garden.io
- [ ] Custom Executor for Scheduler
- [ ] Add Creating the job to the GUI (this is just an API call and validation now)
- [ ] Fix alignment when creating a job through the "wizard"
- [ ] Add scheduling from normal request/Pour it again page
- [ ] Implement the Job List View
- [ ] Delete job from the GUI
- [ ] Trigger validation/error rendering on create job page
- [ ] Clean up JS/Refactor Job portion
- [ ] Cancel jobs that are failing

The hardest part of this is going to be: Custom Executor for Scheduler/Job Listener/Cancel jobs that are failing. The actual feature is that we need to cancel jobs that are failing, we can handle that in one of many ways. Right now, our executor is a Tornado Executor which means that we (in theory) could stop our API, which would be less than good.  

No matter what, we need to execute these job runs in a separate process so that nothing stops our API server. Unfortunately, the built-in process pool executor to apscheduler will not do because it spawns a copy of our API server, which is not good. So we will probably need to create our own executor. If we do create this in a separate process, this means our job runner can actually take more time to determine if a success completed successfully or not. It could also update the database and give us more information about a job's failure. 

Alternatively, we could update the database through a scheduler listener, but I don't see the point if we break things out into their own processes. The final thing about this, is we need to decide on a good way to track job failures. Should we just do counts? or should we create reference fields on the jobs? I think I'd prefer counts because its less data.
