### ISSUE TITLE
Local runs of integration tests

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/beer-garden#1073]
We need the ability to run BEERGARDEN integration tests on our workstations on a local branch.

#### Decisions:
* Is it better to run on only a single or a couple of versions of Python and dependencies? Then the tests would run quickly and wouldn't bog down the workflow process much. In that case, the tests would serve as a gut check that we haven't done anything crazy and broken everything.
* Is it better to run the full matrix of versions? In that case, we'd have strong evidence of the outcome of the tests when they're fired by GitHub actions at midnight. But it can take a long time to run.

#### Potential solutions:
1. Create a python tool that exactly mirrors the steps taken by the actions. Using the `docker` library for python should make many of the steps somewhat easy, though there are some steps in the actions that would take some work.
2. Create a python or bash script that mirrors the intent, but not the exact steps, taken by actions. Both of these options would require maintenance as the actions mature and the versions get bumped.
3. Wait for `act` to become usable without jumping through hoops. This has the benefit that the tests would live in only one place. The downside is that there's no knowing how long this will take (could be years, or days...).

**Comment by scott-taubman** [comment]
For now, it seems like the only realistic path forward is to rework the integration tests to run via some custom script (Makefile probably makes the most sense) and then update the github actions to just leverage that custom script.

Ultimately the goal would be:
* It's possible to run the integration tests locally, at least for some pinned versions of all the things (i.e. not the full matrix of versions).
* The integration tests run on PRs, also for some specific pinned versions.

Ideally, when running things locally we can avoid conflicts with people's running dev environments. For instance, some of us run the required services in containers.  It should not be necessary to tear down those containers in order to run the integration tests.
