### ISSUE TITLE
Update apispec swagger library to 21st century version

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/beer-garden#1124]
We are pinned at apispec v. 0.38.0 as of the last release. The current version is 5.1.0.

By staying with the legacy version, we do not have access to documentation for the library on, say, readthedocs.

Naturally, much has changed as the library matured, so there will be a little work involved. For example, `APISpec.definition()`,  which is used extensively in the `__init__.py` file under `src/app/beer_garden/api/http`, isn't part of the modern library (and hasn't been since before its 1.0 release).

**Comment by kvig** [comment]
I looked into this for a bit today, this old(9/2018) version 0.38 of apispec is also causing the error message in #1240. Upgrading the library should resolve the warning message since the codepath looks different between latest and 0.38.

This doesn't look like a great idea right now since we would have to upgrade brewtils because of the loss of marshmellow 2.

Here's a short summary of the dependency changes from 3.0 to latest (as of 5/2022):
v5.2.0(4/2022) drops python 3.6 support but gets updated to test against 3.10
v4.0.0(9/2020) drops python 3.5 support and marshmellow 2, switches to only 3.x
v3.0.0(9/2019) drops python 2 support

**Comment by scott-taubman** [comment]
After discussion, based on the options presented we're not going to pursue any changes here.
