### ISSUE TITLE
Define Command Outputs

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#13]
For each command, it would be nice if we were able to tell what the plugin was going to respond with

Let's say I have a plugin **`foo`** that responds to command **`bar`** with JSON:
```python
{
  "foo": "bar",
  "baz": "bat",
}
```

There is no good way to tell BEERGARDEN that the above if the expected output. If there was a way to tell BEERGARDEN that, we would suddenly know a lot more about how a plugin is operating, and whether or not what it responds with is expected or unexpected. This would enable-us to create a flow-based GUI/system.

**Comment by hazmat345** [comment]
I'm not sure I agree with this:

> There is no good way to tell BEERGARDEN that the above if the expected output.

I'd think the way you'd do this would be by raising an exception?

**Comment by hazmat345** [comment]
Ok, I'm going to interpret this as saying we should be able to provide some sort of type-hinting behavior for plugin outputs so that we can make guarantees for downstream plugins.

**Comment by loganasherjones** [comment]
Yeah, this issue is for the long-term goal of being able to easily tie the output of one plugin to the input of another plugin. Essentially, the idea would be to enable us to create flow-based plugins without ever having to write code. Does that make any sense?

**Comment by TheBurchLog** [comment]
Thinking about how this would work when a developer is doing their annotations.

In the current version someone would write their command like:
```python
@command(output_type="JSON")
def my_command(self):
    return {"str": "value", "nums": [1, 17], "obj": {"nested": "sweet"}}
```

If we wanted to start mapping out multiple outputs, it would currently look like this. This gets stored in the Request Output as an array.

```python
@command()
def my_command(self):
    return (obj, obj)
```

In order to know what these results are, we could make singular and plural version of fields for labels, types, and classes. We would have to do validation to ensure they don't mix Singular and Plural options, or we could use one field and just do a type check between string and list.

```python
#Defining labels that could be presented in the UI
@command(output_labels=['object1','object2'])
@command(output_label='object1')

#Defining the expected output class type
@command(output_classes=[Str, List])
@command(output_class=Str)

#Defining the multiple output types for presentation on the UI
@command(output_types=["JSON","HTML"])
@command(output_type="JSON")
```

Once we get this working, then we could look at creating UI driven flows from plugins like @loganasherjones mentioned above.
