### ISSUE TITLE
Dynamic choices spawn extra requests

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/beer-garden#1342]
It has been observed that the request creation page ends up spawning unnecessary requests in certain dynamic choices setups.  

**Example Scenario**
* A command has 3 dynamic choices fields, we'll call them A, B, and C
* B and C are dependent on the value of A.

**Current behavior**
* When loading the request creation page, 5 requests spawn: 1 for A and 2 for each B and C.

**Desired behavior**
* When loading the request creation page, only the request to populate A is spawned.

It is unknown if we have have the data necessary to determine that the requests for B and C should be deferred.  The requests do run again once a selection is made for A, so that would seem to indicate that the relationship is known.  Also worth noting is that when the requests are spawned after a selection is made for A, it is only a single request each for B and C, not the duplicate requests.

If the requests for B and C cannot be feasibly deferred, it should be the case that only 1 instance of each requests spawns rather than 2.

**Comment by catattack05** [comment]
To write up where I'm at, I actually don't think this is a UI issue. I think it may in fact be a brewtils parsing issue. Specifically looking into one of the internal parsing functions in choices.py. 
[https://github.com/beer-garden/brewtils/blob/develop/brewtils/choices.py#L85](url)
```
def _parse(_input_string, _parser):
        try:
            return FunctionTransformer().transform(_parser.parse(_input_string))
        except (GrammarError, LexError, ParseError) as e:
            raise ParseError(e)
```

In the example promotion plugin, this sub method gets called on to parse the details of the choices of the overall command object's "bonus word" parameter (that's maybe a bad way of phrasing it, but the tree here is essentially overall: "evaluate" command -> its parameters -> choices for the parameter that uses dynamic choices "bonus word" -> details of those choices, which include the function and arguments that make it dynamic. Prior to parsing, the details of bonus word are 

```
get_bonus_suggestions(work_role=${work_role})
```
This seems like more or less what we want, since in the example plugin, this is in fact the value of the dynamic choices for "bonus word". Upon being called, _parse gets told to parse the details like a func (this means what parsing rules to use), and then goes off to use the _parser (apparently using the Lark library and some custom grammar) defined at the very top of the file in order to do that ([https://github.com/beer-garden/brewtils/blob/develop/brewtils/choices.py#L43](url)) FunctionTransformer().transform just splits the result of _parser into a name and args section. Post parsing, the details become: 
```
{'name': 'get_bonus_suggestions', 'args': [('work_role', 'work_role')]}

```
Now it looks like the code thinks get_bonus_suggestions has two arguments both named "work_role". The command object will keep that duplication all the way until the request creation screen. You can actually see it on the screen if you scroll down far enough in the command JSON; there are two work roles listed as arguments in the "bonus word" section. I'm assuming that the presence of 2 work roles is the reason why we have double the number of "work role" related network traffic

As for how to fix it, we could probably try to change the grammar rules or add a catch inside the _parse function to only keep one of those duplicated arguments after the lark parser does its thing. There may be something else a little more clever that I'm not thinking of

**Comment by catattack05** [comment]
Okay, so here's where we are. The extra requests are coming out of [https://github.com/beer-garden/angular-schema-form-builder/blob/develop/src/dynamicChoices.js#L59](url). So it turns out this isn't an UI issue necessarily, and it's also probably not a bug (or at least I think this was intentional behavior). Dynamic choices.js will provide a list of the dynamic arguments inside of form["choices"]["updateOn"]. It also tells form to run a function called "createRequestWrapper" when any of those values change. In the original code, "instance_name" is included by default, so we're going to get at least 1 call for that no matter what. Back over in UI land [(https://github.com/beer-garden/beer-garden/blob/develop/src/ui/src/js/controllers/command_view.js#L62)](url), Beergarden has the function called "createRequestWrapper" that seems to begin triggering the request calls this issue is about. 

So if we have 1 dynamic parameter (in the promotion plugin this was bonus word that needed work role), we'd get 1 request call for the instance name and 1 request call that runs get bonus suggestions based on work role. This is the doubling we were seeing earlier. I think this really only seems to matter on the request creation page initializing, since after that, the arguments will change based on user input one at a time and createRequestWrapper demonstrates exactly the behavior we'd like it to. During initialization of that page they're all updating at once.

However, more complex scenarios were also brought up. What do we do if parameter A depends on both B and C? Based on the code right now we'd have one call for each during initialization, plus that original instance call. This is what I get when I add more dependencies into get bonus suggestions. I imagine if A depended on B and C depended on D, we would get a call for C and a call for D as well.

So some thoughts about what to do with this. If we don't really think that refreshing dynamic arguments whenever the instance name changes is useful, we could cut that out easily and get rid of 1 extra call during init under every dynamic parameter scenario. If we only want 1 call for the rest of the dynamic arguments, we could try maybe configuring createRequestWrapper to only run the first or last time (like only when B would call it) during init and see if that works. I don't love that idea because ideally we want the first value of A to pop up as what you'd actually get with both b and c active (I think if we only looked at C and ignored B, then you'd have to change C to something else and back again before you got the right A result), and we would also need to keep track of how many calls createRequestWrapper would normally make during initialization (because we'll need it after initialization finishes, and we don't really want to change the function's behavior then). That number would have to be different for every command, and it would still look kind of funky past 1 dependency. 

Maybe there's a way to ignore the first n runs of createRequestWrapper and populate A based on the default values of all its n dependencies, then enable createRequestWrapper starting on attempt n+1. That would probably be the best solution to mitigate the initial requests (if there was ONE total parameter that needed it), but would probably need more book keeping. That's why I think this behavior was probably intended, someone decided it wasn't worth the effort of keeping track.

**Comment by catattack05** [comment]
Barring any last minute revelations, we've decided that the thing to do is to put a warning on the documentation about how the dynamic parameter behavior works. If you have any behavior that changes dependencies for dynamic parameters (like if get bonus parameters also changed work roles), that could potentially be destructive during the initialization phase.

**Comment by catattack05** [comment]
I have opened a pull request in beergarden.io to include a warning about this on the documentation.

**Comment by scott-taubman** [comment]
I'm going to close this issue for now.  We will make sure that the React UI does not reproduce this bug, but we're unlikely to fix it in the current UI.
