### ISSUE TITLE
UI distinction between local and remote plugins

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#230]
We currently have something of a trap in the system admin page. There's no visual distinction between a local plugin (that you can start) and a remote plugin (that you can't).

A user could see the start and stop buttons and assume that a running plugin can be stopped and then started again, when for a remote plugin that's not the case.

**Comment by hazmat345** [comment]
For a remote plugin it would also be handy to show the remote IP address or hostname.

**Comment by hazmat345** [comment]
I think this is one of the few things that should be attempted in the angular app.

**Comment by TheBurchLog** [comment]
Resolved, there is now an icon difference on the System Admin page. When hovering over the local plugins, it will state the directory the plugin exists in. We did not expose any information about the remote plugins because there was no clean way for it to be reported up with what was currently being stored in mongo.
