### ISSUE TITLE
Multiline Comment

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#242]
Multi-line comments seem to be stored correctly in the database, but the newlines are getting lost when they're displayed in the UI.

**Comment by scott-taubman** [comment]
Let's attempt to fix this at least on the request view page (the one where you're looking at a single request).  For the request index page, rendering the newlines could potentially make the table unusable because each row would get huge.  We could do things to alleviate that, but given the future of this iteration of the UI, it's easiest to do nothing there.

**Comment by catattack05** [comment]
You can preserve the formatting of the comment by using the <pre> tag in HTMl (that'll include the newlines at the the cost of putting the comment in a box). Let me see if I can find a way to do it that doesn't include making the box
