### ISSUE TITLE
Formatting for Parameters

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#25]
Let's say I have a parameter:

```python
@parameter(key='capital_letters_only', type='String')
def do_something(self, capital_letters_only):
  return capital_letters_only
```

We could probably support the ability for some common filters to be applied to these strings. The real question is, should we allow custom formatting.. As a couple of examples

Built-in Formatting:

```python
@parameter(key='capital_letters_only', type='String', formatting=brewtils.capitalize)
def do_something(self, capital_letters_only):
  pass
```

Custom formatting:

```python
def my_custom_function(s):
  return s[:-1]

@parameter(key='capital_letters_only'. type='String', formatting=my_custom_function)
def do_something(self, capital_letters_only):
  pass
```

**Comment by hazmat345** [comment]
So I think that any value that could be derived from this would be offset by the reduced locality.

I don't think there's any advantage to this over just doing the transform in the command body. Also, would I be able to specify more than one transform if we were to implement this? Also, what happens if the transform fails or changes the type of the parameter?

**Comment by hazmat345** [comment]
Nobody is asking for this, the increased complexity would not be worth it.
