### ISSUE TITLE
Request Index Page Error Handling

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#293]
Right now we don't handle a missing parent request as gracefully as we could. If the search parameters on the requests index page include children with missing parents we get a 404 response back which causes the spinner to not go away.

Just for clarification - this is not a UI bug. This a problem with the API.

**Comment by TheBurchLog** [comment]
Wasn't able to replicate this exactly. I created a parent/child request and deleted the parent within Mongodb. The error I got instead was unable to serialize the parent object because it does not exist. The pruner will eventually clean these requests up. So it acts like the entire request was deleted, even though it is still in the database.

**Comment by TheBurchLog** [comment]
Correction, we do not have a pruner dedicated to cleaning up orphaned requests. We only handle orphaned requests if it was `IN_PROGRESS` or `CREATED`, not `SUCCESSFUL`. 

Ticket #1656 should solve this

**Comment by TheBurchLog** [comment]
Closing since #1656 will fix this issue by pruning.
