### ISSUE TITLE
Base64 file parameters

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#368]
This is a stopgap / alternative to #288.

There are several things holding up support for "real" file parameters. The most critical of these is that creating a Request has to become a multi-stage process - instead of submitting everything at once the file parameters must be uploaded and then the actual request created.

We could possibly sidestep that particular issue by instead support base64 encoded files as pure parameters. We already have a mechanism in the UI to support this (it would need to be tweaked to not display the value in the `preview`).

The obvious limitations are the size constraints - the files will be stored in Mongo as strings and will be placed on the message queue. However, there may be ways to enforce a sensible size constraint.

We would need to add a new `Parameter` type, and it would definitely not be `file` - this would need to be clearly and obviously distinct from a "real" file parameter.

**Comment by hazmat345** [comment]
Here are things that I think need to be done for this, YMMV:

### Brewtils
- [ ] There needs to be a new thing added to `brewtils.models.Parameter.TYPES`. This is the thing that will 100% not be called "file" - maybe "base64" or something.
- [ ] Translating the parameter before calling the client function. I'm not 100% sure this is necessary, but it would be nice (probably should be done last). This would be similar to what's already in `brewtils.request_handling.RequestProcessor._invoke_command` where we "resolve" a file before invoking the command. We would write out the base64 file to disk in the plugin's _working_directory and pass the file object to the `@command` method (instead of just passing the base64 string and making plugin writers deal with it).

### SchemaFormAddons
- [x] A display widget thing needs to be created to allow a user to specify one of these new parameters in a reasonable manner. There's already a proof of concept here, but IDK if @loganasherjones made it robust, so it may need to be tweaked.

### SchemaFormBuilder
- [] Needs to be able to translate the Parameter type from brewtils ("base64") into the correct schema and form values to display the new file picker widget thing.

### SchemaFormBuilder / Beergarden UI
- [] The current behavior is to display the model value for each parameter in the Preview display. This isn't going to work for this particular case as a base64-encoded file string is going to be enormous and not helpful. So this'll need some special handling - maybe display the file name instead?

I *think* that should be everything that needs to happen. Things that probably don't need to be modified:
- Special handling on the database side. I think we already have a mechanism to failover into GridFS when the parameter is too big. If that's not true then that will probably need to be added (we already do this for request output).
- Worrying about putting this on the message queue. This kind of ties into the above, but it's probably OK to not worry about it for now. If it becomes an issue we can impose a size restriction.

**Comment by hazmat345** [comment]
Here's the order I'd go about this:

- Add the new name to brewtils TYPES.
- Now you can add a new `@command` to one of the example plugins that defines a parameter with that new type:
```python
@parameter(key='the_file', type='base64')
def my_new_method(self, the_file):
    logger.info(the_file)
```
- Now when you go look at that command in the Beergarden UI you can use the three debug displays at the bottom. In the "Command" display you should be able to find the parameter definition for `the_file`, and the `type` field should be the new type you just created
- The next thing is getting the file picker widget to display for this parameter. This will probably be where you need to modify the SF Builder to map the "brewtils type" into the "schemaform type". (This mapping is why string parameters look different than date parameters). You should just need to define the relationship for the new type here since the "schemaform type" has already been created (aka, the filepicker is already a thing that exists). This step is done once you can see the filepicker widget in the Beergarden UI.
- Next thing is making sure the file picker widget works correctly inside the Beergarden UI. You should be able to select a file and have it display the base64 string in the preview pane (probably want to pick a small file here so you don't crash your browser).
- Then verify that things actually work. When you Make Request the request should be processed and executed by the plugin. If you're using the example above the logger should log the base64 string.
- Modify the UI so that the base64 string doesn't show in the preview, but still sends the actual data when making the request (whatever you do here shouldn't break the previous step).
- Extra Credit: Modify the brewtils RequestProcessor so that the plugin gets a file object, not a base64 string (the logger should log <File: asdfwet> or something like that)

**Comment by TheBurchLog** [comment]
When testing this, please make sure the following actions are functional.

- [ ] Executing a command that receives the file object through the UI upload
- [ ] Executing a command on a child garden that receives the file object through the UI upload
- [ ] Executing a command through SystemClient that uploads a file object

**Comment by TheBurchLog** [comment]
@SpecificallyGravity 

What happens in the following scenarios?

1. A String Parameters passes forward a valid File ID?
1. A second Request is made with the same FileID? Who is the owner of that file? (Done through manually editing the JSON in our UI)
1. What happens to the File after a JOB is deleted?
1. What happens when you schedule a JOB via Date/Timestamp that has a file? Does the file get deleted before the Request can be processed? Try this with a larger file that takes a minute to download.
1. What happens when you cancel the upload via the UI, does it send a delete request? (I forgot to look for this during the code review)
1. What happens when a file with none Base64 characters is uploaded?

**Comment by SpecificallyGravity** [comment]
@TheBurchLog 

1. Since we aren't actively checking the parameter field type, this should be resolved as if it were a `Base64` parameter.
2. `set_owner` is called when a new `REQUEST_CREATE` or `JOB_CREATE` event occurs, and ownership priority is as follows: `Job` (highest) -> `Request` -> Custom (lowest).  If a match in priority is found, the most recent ownership claim wins.
3. As long as the `set_owner` function has established a `Job` owns a `File` **before** the `Job` is deleted, when the `Job` is deleted, the `File` and corresponding `FileChunk`s are as well.
4. As mentioned above, the `File` should be deleted alongside the `Job`.  Even if a `Request` is created, the priority handling schema won't allow it to override a `Job` owner.  This becomes a timing issue; I'll revisit this.
5. In the UI the user is prompted to confirm uploading the file; if `cancel` is selected there, nothing is ever sent.  During the upload process, if the user selected the `remove` (x) button next to the file name a `DELETE` request is sent to Beer Garden.
6. Beer Garden doesn't check for valid base64 text right now, which was intended to allow users to store data in their own formats (for example just text strings) if they use the API **only**.  Because the UI and `EasyClient` encode and decode the data as base64, if a user tries to retrieve non-base64 encoded data via the `EasyClient` they will either get garbage data or raise an error decoding it.

**Comment by TheBurchLog** [comment]
@SpecificallyGravity 

One more question.

1. What happens when you click Pour It Again on the Requests page?

**Comment by SpecificallyGravity** [comment]
1. The file ID is auto-populated, so as long as the `File` still exists with Beer Garden, the new `Request` can gain ownership of it.
