### ISSUE TITLE
Multiple entry point startup procedure

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#518]
Right now we're being kind of lazy about how the local plugin startup process is kicked off. We wait for the entry point started event to be handled by the app module and immediately start the local plugins.

We should instead track the status of *all* entry point startups and only start the local plugins when all are ready.

We should probably also publish the garden started event at that point as well, rather than waiting until the very end of the application startup.

**Comment by TheBurchLog** [comment]
I agree that we should wait until all Entry point are online before published the Garden Started Event. I am not 100% right now on the local plugins because we only need the HTTP Entry Point online for local plugins to run. If we are waiting for other Entry Points to start, then there is nothing holding back Local Plugins.

So what I am thinking is we add something to the Entry Start event to indicate which Entry Point it is. Then go back to the Entry Manager to update the status. Then once all of them are online, we can publish a Garden Started Event. 

Then the Garden Started Event will kick off Local Plugin Scan.

**Comment by hazmat345** [comment]
This just became a higher priority now that #529 has been merged.

**Comment by hazmat345** [comment]
@TheBurchLog @west270 #757 has made this an urgent issue. The stomp entry point always "starts" and I'm seeing local plugins fail to start because they started before the HTTP entry point did.

I just pushed 316f4af5 up as a stopgap.

**Comment by TheBurchLog** [comment]
This reverts back the functionality as it was before, and adds granularity in the event through the metadata.
https://github.com/beer-garden/beer-garden/pull/800

**Comment by TheBurchLog** [comment]
Looks like tis all works as expected and waits for HTTP entry point to start up
