### ISSUE TITLE
Local plugin shutdown concurrency

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#567]
When we go to shut down local plugins we wait the shutdown timeout consecutively for all the plugins. We should be doing that wait concurrently.

**Comment by TheBurchLog** [comment]
This should probably be done at the same time as this other ticket: https://github.com/beer-garden/beer-garden/issues/548

**Comment by TheBurchLog** [comment]
I am looking at ways we could improve this and here are the different approaches.

1. Make all instances a sub-process to a super thread that we can run `thread.join` on. That way everything is killed with a single command.
1. Send STOP commands over RabbitMQ to all local plugins and then iterate through the threads to stop. Giving three attempts to kill.
   1. Rabbit MQ Stop
   1. Thread Join
   1. Kill
1. Continue to iterate through all threads to join
1. Convert over to something like ThreadPools where everything can be killed at once. (probably won't work because of worker limitations.)

**Comment by TheBurchLog** [comment]
Taking another look at this. If we try using the Threading functions `PluginManager.instance().join(timeout=30)` or `PluginManager.instance().stop()` then all of the Local Plugins will shutdown concurrently. This issue with this is the amount of errors that get thrown in the logs. The Entry Point for HTTP gets shutdown and the plugins throw errors when they attempt to publish their stop event.
