### ISSUE TITLE
Better routing logic for non-routable operations

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#576]
Currently the routing logic is slightly backwards. We "parse" and operation and determine which garden an operation should be addressed to. Only right before we attempt to forward the operation do we check to see if it's in the list of "allowed" forwardable operations (and raise if it isn't).

We should just assume that everything that *isn't* forwardable is addressed to the local garden from the start.

This ticket was originally only related to routing the SYSTEM_UPDATE event:
~In the router, move System Updates to local garden events only. Plugins are the only BG entities that call this function and they can only be local.~

**Comment by hazmat345** [comment]
And of course, as soon as I update this ticket I think I remember why we *don't* do this.

Let's assume that we decide that INSTANCE_STOP events are not routable. Cool, but we don't have anything that disables the stop icon on the systems admin page for non-local plugins. If we switch to the setup described in this issue, when the user clicks that button they'll see an error to the effect of "instance could not be found", which is *true* since that instance lives on another garden, but the error should really be "you tried to execute an un-forwardable operation on another garden."

Determine the "correct" garden first allows us to do this correctly.

@TheBurchLog after all of this I think the way we're currently doing this actually the best way, and that this should be closed as a wontfix. Thoughts?

**Comment by TheBurchLog** [comment]
@hazmat345 

I just looked over the routing paths we have and I think we are going to run into some issues. For example, reading the plugin logs are not being forwarded to the downstream Beer Garden. 

I think we should go through each route and make the determination on whether of not it should be forwarded to a child Garden.

I do agree we are doing the logic correctly to determine if it is something that the local garden should handle.

**Comment by TheBurchLog** [comment]
Created a new issue to handle the "What should we forward" question. #659

**Comment by hazmat345** [comment]
Closing as wontfix.
