### ISSUE TITLE
Can Create Two Gardens with same name through the API

### ISSUE THREAD

**Issue by west270** [beer-garden/beer-garden#727]
When working on issue #726, I was able to make two gardens with the same name.

The UI protects against creating a garden with a duplicate name, but there is currently no validation on the api side. We should add a unique constraint at the database model level, which should translate to the right HTTP status code getting returned when someone attempts to create a duplicate garden name.

**Comment by scott-taubman** [comment]
I'll put this comment here, though maybe it deserves its own ticket...

Related to Garden naming, I've noticed that you can create garden names with non-word characters, like "-", but then you can never get them again via the API.  So I can create a Garden named "who-loves-hyphens", but then if I try to go to `/api/v1/gardens/who-loves-hyphens/` I get an immediate 404, presumably because that path doesn't match any of the defined routes, which look for word characters (`\w`) only.

Presumably we should either:
  * Fix the routing so that you can reach endpoints for all legal garden names
  * **or** validate that the garden name contains only word characters before we create it

The reason why this may be appropriate as one issue is because the broader problem appears to be garden name validation, which is maybe just non-existent today?  At a minimum, it needs some attention.

**Comment by hazmat345** [comment]
@scott-taubman I think #940 is tracking that issue.

**Comment by scott-taubman** [comment]
Looks like you're right. URL encoding works as it should. We'll address that in #940 then.

**Comment by scott-taubman** [comment]
A possibly ignorant follow-up question...What's the theoretical downside to just being less strict in the routing regex?  Why only route stuff that matches `[\w%]+`, as opposed to routing whatever is supplied? Worst case should be that they get a 404 back right?  Granted, it's more work to do the lookup to return that 404, but the upside is that you don't have to codify the acceptable garden name format in another place.
