### ISSUE TITLE
Child Garden Sync Handling

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#748]
When a child is rebuilt, the System IDs no longer match what is locate din the parent. This causes a duplicate database entry record to occur. We need to figure out a good course of action to resolve this issue.

Options:
1. Require System Admins to delete the System through the UI and then force a Garden Sync.
1. When a Garden Shutdown Event is captured, delete all associated systems
1. When a Garden Shutdown Event is captured, mark all systems as shutdown. Then add logic to allow new systems to be created with same unique values if the original is shutdown, but if the `System.id` is provided that doesn't match then delete the original.

I am leaning towards option 3.

**Comment by TheBurchLog** [comment]
@hazmat345 Lets sync about this later

**Comment by TheBurchLog** [comment]
To accomplish this it has two actions that we need to take.

1. Bulk Action feature on they System Admin page. Something that will allow you to Start/Stop based on Namespace or System Name or System Version.
1. Marking Systems in a different status when garden is shutdown. Enabling them to be rebuilt with new ids if required.

**Comment by scott-taubman** [comment]
I don't have the context for some of the original suggestions relating to "Garden Shutdown" events (`SHUTDOWN` isn't even one of the garden related event types), so I suggest that we start by seeing if we can do the simplest possible thing, which to me seems like it would be to just delete any systems not present during the garden sync before we go and create new ones.  That is, if a system exists in the local DB for which there is no system with a matching id present in the sync data, delete that DB entry.  Then after you've done that cleanup, proceed with the create / update of the remaining systems in the sync data.

It has been suggested that this problem is more than just an issue of mismatching IDs and that even cases where a new system version is present don't behave correctly.  That's why I suggested we "start" with the above and see where it gets us.  That strategy may not be viable for reasons that won't be clear until we explore it and even if it is viable it may not be the whole solution.

**Comment by scott-taubman** [comment]
I'm struggling to see the distinction between this one and #1101 so I'm going to close this as a duplicate and track that one, since I think the description there more clearly communicates the issue.  I'll copy my previous comment on this issue over to that one.
