### ISSUE TITLE
SystemClient refer to current system by default

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#780]
We should consider making a `SystemClient` refer to itself by default.

This change would solve or improve several cases of weirdness relating to SystemClient usage:

- Currently, if no instance name is provided when constructing the `SystemClient` then the literal value `default` will be used. This makes running plugins with a single instance *not* named "default" kind of strange.
- The default behavior of the "version" parameter (if no version is provided use the "latest" version) is also an issue. If a `SystemClient` is created with the goal of making requests against the current plugin the current behavior encourages the assumption that developers don't need to worry about the version. However, if a new version of the plugin is deployed the behavior of the original plugin will change the next time it's restarted - its `SystemClient` will now be making requests on the *new* version!

This would be an extension of the global configuration concept. These would be the concrete changes. For each case the behavior represents what happens if the given parameter is *not* provided, if the parameter is provided that value would obviously be used:
Parameter | Prior | New
--------- | ----- | ---
`system_name` | required | would be assumed to be the current running plugin's system name
`version_constraint` | "latest" | will be the current running plugin's system version if the `system_name` is the current plugin's system name. otherwise will remain "latest"
`default_instance` | "default" | will be the current running plugin's instance name if the `system_name` and `version_constraint` match the current running plugin. otherwise will remain "default"

**Comment by TheBurchLog** [comment]
This sounds like an interesting feature, but it could get complex when determining the default values.

What if instead we have developers just call the function via `self.`? Just like standard python. 

To make this work with remote requests, we would have to set a flag in the plugin configuration for something like `generate_self_requests`. Then when a function has the `@command` annotation we can pre-process the request. If the flag is True, then we return back the results of a System Client that is targeted at the System/Version constraints. We would also have to do a check on if the `request` object is targeted at the function being called, if it is, then execute the command locally.

I think doing it this way would make it easier for Plugin Developers to call the local client and would keep their code cleaner. 

Example:

```python

@command()
def function1(self, var1):
    return var1

@command()
def function2(self, var2):
    return self.function1(var2)
```

instead of

```python

def __init__(self):
    self.local_client = SystemClient()

@command()
def function1(self, var1):
    return var1

@command()
def function2(self, var2):
    return self.local_client.function1(var2)

```

**Comment by hazmat345** [comment]
I know we talked about this, so I'm just jotting this down for posterity.

My main objection to that is I think it strays too far away from expected behavior. Invoking an attribute method is a core part of how the language works, and if we mess with that it's going to be very surprising to people.

The neat part is that your second example can actually be simplified even further since there's no need to keep a `SystemClient` around at all, assuming you don't mind the extra overhead of checking the system every time:


```python
@command()
def function1(self, var1):
    return var1

@command()
def function2(self, var2):
    return SystemClient().function1(var2)
```
