### ISSUE TITLE
File-based transport

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#876]
- [ ] Entry point that watches directory for operation files
- [ ] Sending operation to child garden drops a file in a directory instead of using HTTP

**Comment by TheBurchLog** [comment]
This needs to support both Entry Point and Garden Connection, and Parent Connection for Files.

Decisions:
Inbound files, do files get deleted after being processed?
Inbound files, what happens when files are already in the inbound directory at startup?
Inbound files, are files unique based on File Hash or File Name?
Inbound files, does BG track which files have been processed?
Inbound files, do we prioritize existing files based on creation or modification date?

Outbound files, how do we name the files?
Outbound files, should we have a file limit?

Connection Parameters, what happens when multiple in-bounds are monitoring the same directory?
